# Generated by Django 4.2 on 2023-04-19 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='undecided', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='undecided', max_length=255)),
                ('date_of_birth', models.DateTimeField()),
                ('countOfFilms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='movies_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=255)),
                ('premier_date', models.DateField()),
                ('description', models.TextField(default='undecided', max_length=600, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('duration', models.DurationField()),
                ('poster', models.ImageField(upload_to='images')),
                ('actors', models.ManyToManyField(related_name='actor_in', to='Movies.person')),
                ('directors', models.ManyToManyField(related_name='directors_movies', to='Movies.person')),
                ('genres', models.ManyToManyField(related_name='Movies', to='Movies.genre')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Movies', to=settings.AUTH_USER_MODEL)),
                ('writers', models.ManyToManyField(related_name='writers_movies', to='Movies.person')),
            ],
            options={
                'ordering': ['duration'],
            },
        ),
    ]
