# Generated by Django 4.2 on 2023-04-14 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='undecided', max_length=255)),
                ('premier_date', models.DateField(verbose_name='15-Apr-2023')),
                ('genres', models.CharField(default='undecided', max_length=255)),
                ('description', models.TextField(default='undecided', max_length=600)),
                ('directors', models.CharField(default='undecided', max_length=255)),
                ('writers', models.CharField(default='undecided', max_length=255)),
                ('actors', models.TextField(default='undecided', max_length=600)),
                ('rating', models.FloatField(default=0, max_length=10)),
                ('duration', models.TimeField(verbose_name='03:50:21')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['duration'],
            },
        ),
    ]
