# Generated by Django 4.2 on 2023-04-18 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='undecided', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='undecided', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='undecided', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Writers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='undecided', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MoviesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premier_date', models.DateField()),
                ('description', models.TextField(default='undecided', max_length=600)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('duration', models.DurationField()),
                ('poster', models.ImageField(upload_to='')),
                ('actors', models.ManyToManyField(related_name='Movies', to='Movies.actors')),
                ('directors', models.ManyToManyField(related_name='Movies', to='Movies.directors')),
                ('genres', models.ManyToManyField(related_name='Movies', to='Movies.genre')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Movies', to=settings.AUTH_USER_MODEL)),
                ('writers', models.ManyToManyField(related_name='Movies', to='Movies.writers')),
            ],
            options={
                'ordering': ['duration'],
            },
        ),
    ]
