# Generated by Django 4.2 on 2023-04-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesdata',
            name='name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
