# Generated by Django 4.2 on 2023-04-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_moviesdata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesdata',
            name='description',
            field=models.TextField(default='undecided', max_length=600, null=True),
        ),
    ]
