# Generated by Django 4.2 on 2023-04-18 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Movies', '0004_alter_moviesdata_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesdata',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
