# Generated by Django 4.2 on 2023-04-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0005_alter_moviesdata_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesdata',
            name='poster',
            field=models.ImageField(upload_to='images'),
        ),
    ]
